### ISSUE TITLE
This is what I did in the Python shell.

### ISSUE THREAD

**Issue by htmlcoder1562** [The-Cloud-Dev/scratch2py#37]
<h1>My code:</h1>

```python
from scratch2py import Scratch2Py as s2p
s2py=s2p("fhghfvhgfv", "SECRET")
cloud=s2py.scratchConnect(1047391965)
cloud.setCloudVar("running", 1)
cloud.setCloudVar("running", 1)
```

<h1>The error at the last line:</h1>
``` 
Traceback (most recent call last):
  File "<pyshell#39>", line 1, in <module>
    cloud.setCloudVar("running", 1)
  File  #"C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scratch2py\__init__.py", line 454, in setCloudVar
    ws.send(json.dumps({
  File "C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 283, in send
    return self.send_frame(frame)
  File "C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 311, in send_frame
    l = self._send(data)
  File "C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 525, in _send
    return send(self.sock, data)
  File "C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_socket.py", line 170, in send
    return _send()
  File "C:\Users\nolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_socket.py", line 147, in _send
    return sock.send(data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1242, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2427)
```

**Comment by htmlcoder1562** [comment]
By the way, an easier way to respond is message me on Scratch: [@fhghfvhgfv](https://scratch.mit.edu/users/fhghfvhgfv)

**Comment by The-Cloud-Dev** [comment]
It's been years since this Library was updated, it doesn't conform to the new protocols for sending WebSocket messages. I unfortunately do not have the time to update it and hence will not be able to fix this. I'd recommend you use ScratchConnect as it is kept up-to-date.
